controllers/AdminController.php
<?php
namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use SplFileInfo;
use app\models\Category;
use app\models\CategoryForm;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Product;
use app\repository\StoreService;
use yii\helpers\ArrayHelper;


class AdminController extends Controller
{
        
    public function actionIndex()
    {
        return $this->render('index');   
    }
    
    public function actionAddcategory()
    {
        $model = new CategoryForm;
        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            $category = new Category();
            $category->parent_id = $model->parent_id;
            $category->cat_name = $model->cat_name;
            $category->save();
            
            return $this->redirect(['site/index']);
        }
        return $this->render('addcategory', ['model' => $model, 'arr' => StoreService::ArrCategories()]);
    }    
    
    public function actionGetproducts($product)
    {
        return $this->render('getproducts', ['product' => $product]);
    }
        
    public function actionUpload()
    {
        //StoreService::UploadFile();
        $myservice = new StoreService();
        $result = $myservice->UploadFile();
        return $this->render('upload',['result' => $result]);
    }
   
    public function actionGetfiles()
    {
        $myservice = new StoreService();
        $listfiles = $myservice->GetFiles();
        return $this->render('getfiles',['files' => $listfiles]);
    }
    
    public function actionUpdate($file)
    {
        StoreService::Update($file);
        return $this->redirect(['site/index']);
    }
    
    public function actionUpdateall()
    {
        StoreService::UpdateAll();
        return $this->redirect(['site/index']);
    }
    
}

views/admin/addcategory.php
<?php
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use app\models\Product;
use app\models\Category;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Add category';
$this->params['breadcrumbs'][] = $this->title;
?>
<h3>Category form</h3>

<?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'cat_name')->textInput(['placeholder' => 'Category', 'style'=>'width:300px'])?>
   <?= $form->field($model, 'parent_id')->dropDownList($arr, ['style'=>'width:300px'])?>
    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary'])?>
<?php ActiveForm::end() ?>

views/admin/getfiles.php
<?php
use yii\helpers\Html;

$this->title = 'Update';
$this->params['breadcrumbs'][] = $this->title;
?>

<div>
  <h1><?= Html::encode($this->title) ?></h1>
  
  <ul class="list-group">
        <?php foreach ($files as $file): ?>
            <li class="list-group-item">
                <?php echo $file ?> 
                <?= Html::a('Update', ['admin/update', 'file' => $file], ['class' => 'btn btn-default']) ?>
            </li>
        <?php endforeach;?>
  </ul>
  <?= Html::a('Update all', ['admin/updateall'], ['class' => 'btn btn-default']) ?>
  
</div>

views/admin/getproducts.php
<?php
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use app\models\Product;

$this->title = $product;
$this->params['breadcrumbs'][] = $this->title;

echo GridView::widget([
            'dataProvider' => Product::Search($product),
]);

views/admin/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Admin';
$this->params['breadcrumbs'][] = $this->title;

?>

<div >
  <h1><?= Html::encode($this->title) ?></h1>
  
  <ul class="list-group">
    <li class="list-group-item"><?= Html::a('Upload file', ['admin/upload']) ?></li>
    <li class="list-group-item"><?= Html::a('Update files', ['admin/getfiles']) ?></li>
    <li class="list-group-item"> <?= Html::a('Add new Category', ['admin/addcategory'], ['class' => 'btn btn-default']) ?></li>
  </ul>
</div>

views/admin/upload.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Upload';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php if($result != "")
    {
        echo $result;
    } 
?>
<?php $form = ActiveForm::begin(['method' => 'post', 'options' => ['enctype'=>'multipart/form-data']]); ?>
    <input type="file" name="myfile"/>
    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
<?php $form = ActiveForm::end(); ?>